language: node_js
node_js:
- "14" 
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: Build
      name: Build
      script:
        - npm run build
deploy:
  branch: main
  provider: heroku
  api_key:
    secure: b2371e11-42f3-415c-ae61-80bb0a8091ae